version: '2'
services:
  sentinel1:
    image: redis       ## 镜像
    container_name: ufire-redis-sentinel-1
    ports:
    - "26379:26379"
    networks:
     redis_network:
      ipv4_address: 172.30.0.22 
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - "./sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
  sentinel2:
    image: redis                ## 镜像
    container_name: ufire-redis-sentinel-2
    ports:
    - "26380:26379"
    networks:
     redis_network:
      ipv4_address: 172.30.0.23           
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - "./sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
  sentinel3:
    image: redis                ## 镜像
    container_name: ufire-redis-sentinel-3
    ports:
    - "26381:26379"
    networks:
     redis_network:
      ipv4_address: 172.30.0.24          
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - "./sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
networks:
  redis_network:
    external: true